// Report automatique des journées non saisies (MAXI-AGRO).
// Si un agent oublie d'enregistrer une saisie, l'appli crée automatiquement un
// inventaire de REPORT pour la/les journée(s) manquée(s) — Y COMPRIS le jour même
// (snapshot d'OUVERTURE), de sorte que le stock du jour est toujours persisté même
// si personne ne saisit :
//   - EF Initial = dernier EF Final CONNU par espèce (report de la veille),
//   - aucun mouvement manuel (la nouvelle journée repart « à zéro »),
//   - mais les SORTIES sur demande approuvée de ce jour-là sont décomptées.
// Ainsi l'historique reste continu et aucune sortie n'est perdue. À minuit, le
// EF Final de la veille devient donc l'EF Initial du jour (roll automatique).
//
// Garde-fous :
//   - On attend que le RÉFÉRENTIEL soit synchronisé (store.ready). SINON on risque
//     de générer un report avec la liste d'espèces PAR DÉFAUT (défaut d'usine) et de
//     perdre les espèces personnalisées → tout retombe à 0 sauf une (bug « 88 / 00 »).
//   - Report ROBUSTE PAR ESPÈCE : l'EF Initial de chaque espèce provient du dernier
//     inventaire qui CONTIENT réellement cette espèce (pas seulement de la veille),
//     ce qui résiste à un document tronqué au milieu de l'historique.
//   - Le report du jour n'a PAS de `savedAt` : l'agent peut toujours saisir et son
//     enregistrement écrase le report.
import { useEffect, useRef } from 'react'
import { useCollection } from '../../hooks/useFirestore'
import { useAgroStore } from './store/agroStore'
import { setItem } from '../../core/db'
import { autoSorties } from './logic'
import { todayStr, addDays } from '../../utils/formatters'

const MAX_JOURS = 60 // borne de sécurité (évite un backfill massif si longue inactivité)

// Dernier EF Final CONNU d'un article, en remontant l'historique (trié croissant).
// On ne considère QUE les documents qui contiennent explicitement la clé de l'article
// (une espèce absente d'un document tronqué est ainsi « réparée » depuis le dernier
// document où elle existait, au lieu d'être perdue).
function dernierFinConnu(historique, id, kind) {
  for (let i = historique.length - 1; i >= 0; i--) {
    const v = historique[i]?.[kind]?.[id]
    if (v && v.fin !== undefined && v.fin !== null) return v.fin || 0
  }
  return 0
}

// Construit l'inventaire de report d'une journée à partir de tout l'historique connu.
function construireReport(historiqueAvant, date, especes, aliments, demandes) {
  const animaux = {}
  especes.forEach((e) => {
    const init = dernierFinConnu(historiqueAvant, e.id, 'animaux')
    const autoSor = autoSorties(demandes, e.id, date, 'animal')
    animaux[e.id] = {
      init, naiss: 0, ent: 0, sor: autoSor, dec: 0, malades: 0,
      fin: Math.max(0, init - autoSor), autoSor, entrees: [], sorties: []
    }
  })
  const alim = {}
  aliments.forEach((x) => {
    const init = dernierFinConnu(historiqueAvant, x.id, 'aliments')
    const autoSor = autoSorties(demandes, x.id, date, 'aliment')
    alim[x.id] = {
      init, ent: 0, sor: autoSor,
      fin: Math.max(0, init - autoSor), autoSor, entrees: [], sorties: []
    }
  })
  // Pas de `savedAt` : ce report reste « non saisi » → l'agent peut toujours saisir
  // et son enregistrement écrasera ce document.
  return { date, agentNom: 'Système (report auto)', autoGenerated: true, animaux, aliments: alim }
}

export default function AutoCarryForward() {
  const { data: inventaires, loading: l1 } = useCollection('agro_inventaires')
  const { data: demandes, loading: l2 } = useCollection('agro_demandes')
  const especes = useAgroStore((s) => s.especes)
  const aliments = useAgroStore((s) => s.aliments)
  const referentielReady = useAgroStore((s) => s.ready)
  const ranRef = useRef(false)

  useEffect(() => {
    if (ranRef.current) return
    if (l1 || l2) return // on attend que les données soient chargées
    if (!referentielReady) return // ⚠️ ne JAMAIS reporter avec le référentiel par défaut
    if (!especes.length && !aliments.length) return // référentiel pas prêt
    if (!inventaires.length) return // aucune saisie de référence → rien à reporter

    const today = todayStr()
    const dates = inventaires.map((i) => i.date).filter(Boolean).sort()
    const lastDate = dates[dates.length - 1]
    if (!lastDate || lastDate > today) return
    // Le jour est déjà saisi RÉELLEMENT (savedAt) → rien à faire pour aujourd'hui,
    // mais on comble quand même d'éventuels trous PASSÉS.
    const todaySaved = inventaires.some((i) => i.date === today && i.savedAt)
    if (lastDate === today && todaySaved) return

    ranRef.current = true
    ;(async () => {
      try {
        const parDate = new Map(inventaires.map((i) => [i.date, i]))
        // Historique trié croissant (mutable : on y ajoute les reports créés).
        const historique = [...inventaires].sort((a, b) => (a.date < b.date ? -1 : 1))
        let cursor = addDays(lastDate, 1)
        let created = 0
        // On va jusqu'à AUJOURD'HUI inclus : garantit un snapshot d'ouverture du jour.
        while (cursor <= today && created < MAX_JOURS) {
          const existant = parDate.get(cursor)
          if (!existant) {
            const historiqueAvant = historique.filter((i) => i.date < cursor)
            const report = construireReport(historiqueAvant, cursor, especes, aliments, demandes)
            await setItem('agro_inventaires', cursor, report)
            historique.push(report)
            historique.sort((a, b) => (a.date < b.date ? -1 : 1))
            parDate.set(cursor, report)
            created++
          }
          cursor = addDays(cursor, 1)
        }
      } catch (e) {
        console.warn('[carry-forward] échec report automatique :', e)
        ranRef.current = false // autorise une nouvelle tentative
      }
    })()
  }, [inventaires, demandes, especes, aliments, referentielReady, l1, l2])

  return null
}
