// Report automatique des journées non saisies (MAXI-AGRO).
// Si un agent oublie d'enregistrer une saisie, l'appli crée automatiquement, le
// lendemain, un inventaire de REPORT pour la/les journée(s) manquée(s) :
//   - EF Initial = EF Final reporté de la veille,
//   - aucun mouvement manuel (la nouvelle journée repart « à zéro »),
//   - mais les SORTIES sur demande approuvée de ce jour-là sont décomptées.
// Ainsi l'historique reste continu et aucune sortie n'est perdue.
//
// Garde-fous : on ne touche JAMAIS à aujourd'hui (réservé à l'agent), on ne
// recrée pas une journée déjà saisie, et toute saisie réelle ultérieure de
// l'agent remplace le report (son enregistrement écrase ce document).
import { useEffect, useRef } from 'react'
import { useCollection } from '../../hooks/useFirestore'
import { useAgroStore } from './store/agroStore'
import { setItem, ts } from '../../core/db'
import { getInventaire, autoSorties } from './logic'
import { todayStr, addDays } from '../../utils/formatters'

const MAX_JOURS = 31 // borne de sécurité (évite un backfill massif si longue inactivité)

// Construit l'inventaire de report d'une journée à partir de l'état précédent.
function construireReport(prev, date, especes, aliments, demandes) {
  const animaux = {}
  especes.forEach((e) => {
    const init = prev?.animaux?.[e.id]?.fin || 0
    const autoSor = autoSorties(demandes, e.id, date, 'animal')
    animaux[e.id] = {
      init, naiss: 0, ent: 0, sor: autoSor, dec: 0,
      fin: Math.max(0, init - autoSor), autoSor, entrees: [], sorties: []
    }
  })
  const alim = {}
  aliments.forEach((x) => {
    const init = prev?.aliments?.[x.id]?.fin || 0
    const autoSor = autoSorties(demandes, x.id, date, 'aliment')
    alim[x.id] = {
      init, ent: 0, sor: autoSor,
      fin: Math.max(0, init - autoSor), autoSor, entrees: [], sorties: []
    }
  })
  return {
    date, agentNom: 'Système (report auto)', autoGenerated: true, savedAt: ts(),
    animaux, aliments: alim
  }
}

export default function AutoCarryForward() {
  const { data: inventaires, loading: l1 } = useCollection('agro_inventaires')
  const { data: demandes, loading: l2 } = useCollection('agro_demandes')
  const especes = useAgroStore((s) => s.especes)
  const aliments = useAgroStore((s) => s.aliments)
  const ranRef = useRef(false)

  useEffect(() => {
    if (ranRef.current) return
    if (l1 || l2) return // on attend que les données soient chargées
    if (!especes.length && !aliments.length) return // référentiel pas prêt
    if (!inventaires.length) return // aucune saisie de référence → rien à reporter

    const today = todayStr()
    const dates = inventaires.map((i) => i.date).filter(Boolean).sort()
    const lastDate = dates[dates.length - 1]
    if (!lastDate || lastDate >= today) return // déjà à jour (ou saisie d'aujourd'hui faite)

    ranRef.current = true
    ;(async () => {
      try {
        const existing = new Set(dates)
        const yesterday = addDays(today, -1)
        let prev = getInventaire(inventaires, lastDate)
        let cursor = addDays(lastDate, 1)
        let created = 0
        while (cursor <= yesterday && created < MAX_JOURS) {
          if (!existing.has(cursor)) {
            const report = construireReport(prev, cursor, especes, aliments, demandes)
            await setItem('agro_inventaires', cursor, report)
            prev = report
            created++
          } else {
            prev = getInventaire(inventaires, cursor) || prev
          }
          cursor = addDays(cursor, 1)
        }
      } catch (e) {
        console.warn('[carry-forward] échec report automatique :', e)
        ranRef.current = false // autorise une nouvelle tentative
      }
    })()
  }, [inventaires, demandes, especes, aliments, l1, l2])

  return null
}
