// Report automatique des journées non saisies — MAXI LOGISTIQUE (par SITE).
//
// Assure la CONCORDANCE du stock même si personne ne fait de saisie magasin un
// jour donné : pour chaque site (Lomé / Kara) et chaque jour manqué, l'appli crée
// un inventaire de REPORT qui :
//   - reprend le dernier EF Final CONNU par matériel (report de la veille),
//   - décompte les SORTIES certifiées (autorisations de sortie) de ce jour-là,
//   - RÉINTÈGRE les retours « OK » de ce jour-là (et trace Cassé / Perdu),
//   - EF Final = init − sorties + retours OK.
// Le jour même est aussi couvert (snapshot d'OUVERTURE) : à minuit, l'EF Final de
// la veille devient l'EF Initial du jour, sans perte de sortie ni de retour.
//
// Garde-fous :
//   - On attend la synchro du RÉFÉRENTIEL (store.ready) pour ne jamais reporter avec
//     la liste de matériel PAR DÉFAUT (sinon on perdrait le matériel personnalisé).
//   - Report ROBUSTE PAR MATÉRIEL : l'EF Initial provient du dernier document qui
//     CONTIENT réellement ce matériel (résiste à un document tronqué au milieu).
//   - Le report n'a PAS de `savedAt` : l'agent peut toujours saisir et écraser.
import { useEffect, useRef } from 'react'
import { useCollection } from '../../hooks/useFirestore'
import { useLogistiqueStore } from './store/referentielStore'
import { setItem } from '../../core/db'
import { autoSorties, agregerMateriel } from './logic'
import { SITE_IDS, matchSite } from './site/useSite'
import { todayStr, addDays } from '../../utils/formatters'

const MAX_JOURS = 60

function dernierFinConnu(historique, id) {
  for (let i = historique.length - 1; i >= 0; i--) {
    const v = historique[i]?.materiels?.[id]
    if (v && v.fin !== undefined && v.fin !== null) return v.fin || 0
  }
  return 0
}

// Retours enregistrés (collection logistique_retours) d'un matériel à une date.
function retoursDuJour(retoursSite, materielId, date) {
  return retoursSite
    .filter((r) => r.date === date && r.materielId === materielId)
    .map((r) => ({
      type: r.type, qte: parseInt(r.qte) || 0, motif: r.motif,
      prestationNum: r.prestationNum, agentId: r.agentId, agentNom: r.agentNom
    }))
}

function construireReport(historiqueAvant, date, site, materiel, demandesSite, retoursSite) {
  const materiels = {}
  materiel.forEach((m) => {
    const init = dernierFinConnu(historiqueAvant, m.id)
    const autoSor = autoSorties(demandesSite, m.id, date)
    const retours = retoursDuJour(retoursSite, m.id, date)
    const agg = agregerMateriel({ init, entrees: [], sorties: [], retours }, autoSor)
    materiels[m.id] = { ...agg, entrees: [], sorties: [], retours, autoSor }
  })
  return { date, site, agentNom: 'Système (report auto)', autoGenerated: true, materiels }
}

export default function AutoCarryForwardLogistique() {
  const { data: inventaires, loading: l1 } = useCollection('logistique_inventaires')
  const { data: demandes, loading: l2 } = useCollection('logistique_demandes')
  const { data: retours, loading: l3 } = useCollection('logistique_retours')
  const materiel = useLogistiqueStore((s) => s.materiel)
  const referentielReady = useLogistiqueStore((s) => s.ready)
  const ranRef = useRef(false)

  useEffect(() => {
    if (ranRef.current) return
    if (l1 || l2 || l3) return
    if (!referentielReady) return
    if (!materiel.length) return
    if (!inventaires.length) return // aucune saisie de référence sur aucun site

    ranRef.current = true
    ;(async () => {
      try {
        const today = todayStr()
        for (const site of SITE_IDS) {
          const invSite = inventaires.filter((i) => matchSite(i, site))
          if (!invSite.length) continue // ce site n'a jamais été initialisé → rien à reporter
          const demandesSite = demandes.filter((d) => matchSite(d, site))
          const retoursSite = retours.filter((r) => matchSite(r, site))

          const parDate = new Map(invSite.map((i) => [i.date, i]))
          const historique = [...invSite].sort((a, b) => (a.date < b.date ? -1 : 1))
          const lastDate = historique[historique.length - 1].date
          if (!lastDate || lastDate > today) continue
          const todaySaved = invSite.some((i) => i.date === today && i.savedAt)
          if (lastDate === today && todaySaved) continue

          let cursor = addDays(lastDate, 1)
          let created = 0
          while (cursor <= today && created < MAX_JOURS) {
            if (!parDate.get(cursor)) {
              const historiqueAvant = historique.filter((i) => i.date < cursor)
              const report = construireReport(historiqueAvant, cursor, site, materiel, demandesSite, retoursSite)
              await setItem('logistique_inventaires', `${site}__${cursor}`, report)
              historique.push(report)
              historique.sort((a, b) => (a.date < b.date ? -1 : 1))
              parDate.set(cursor, report)
              created++
            }
            cursor = addDays(cursor, 1)
          }
        }
      } catch (e) {
        console.warn('[carry-forward logistique] échec report automatique :', e)
        ranRef.current = false
      }
    })()
  }, [inventaires, demandes, retours, materiel, referentielReady, l1, l2, l3])

  return null
}
